### ISSUE TITLE
Doest working and output message.

### ISSUE THREAD

**Issue by loopzer** [lancecontreras/RunCustomToolOnBuild#2]
When i build a project this output is showing up:

**[9/23/17 8:04:26.119 RunCustomToolOnBuild] System.ArgumentNullException: Value cannot be null.
Parameter name: pUnk
   at System.Runtime.InteropServices.Marshal.GetTypedObjectForIUnknown(IntPtr pUnk, Type t)
   at RunCustomToolOnBuild.RunCustomToolPackage.GetCurrentProject() in C:\Users\contrerasl\Source\Repos\RunCustomToolOnBuild\RunCustomToolOnBuild\RunCustomToolPackage.cs:line 152
   at RunCustomToolOnBuild.RunCustomToolPackage.BuildEvents_OnBuildBegin(vsBuildScope Scope, vsBuildAction Action) in C:\Users\contrerasl\Source\Repos\RunCustomToolOnBuild\RunCustomToolOnBuild\RunCustomToolPackage.cs:line 97**

And does't make any tt file.

Visual Studio Community 2015 ver: 14.0.25431.01 Update 3
and running as Administrator

**Comment by lancecontreras** [comment]
I'll try to replicate this. Thanks.

**Comment by lancecontreras** [comment]
I managed to replicate this issue and now fixing it.

**Comment by lancecontreras** [comment]
This issue is now fixed in the master branch. Thanks @loopzer!
